version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379/0
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379/0
    command: >
      celery -A tasks worker --loglevel=info --queues data_extraction,data_processing,data_embed_ingest

  flower:
    build: .
    container_name: celery_flower
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5555:5555"
    command: celery -A tasks flower --port=5555

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
